/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yll_self_testapp_jni_MyJni */

#ifndef _Included_yll_self_testapp_jni_MyJni
#define _Included_yll_self_testapp_jni_MyJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yll_self_testapp_jni_MyJni
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yll_self_testapp_jni_MyJni_set
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yll_self_testapp_jni_MyJni
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_yll_self_testapp_jni_MyJni_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
